<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\SimpleArticle;
use AppBundle\Entity\Tag;

/**
 * BonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Tag $tag
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findArticlesByTag(Tag $tag)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:SimpleArticle', 'a')
            ->innerJoin('a.tag', 't')
            ->where('t.id = :tagId' )
            ->setParameter('tagId', $tag->getId() )
            ->getQuery()
            ->getResult();
    }
}
